name: Complete Build - Test, Lint

on:
  workflow_dispatch:
  pull_request:
    branches: 
      - main
  push:
    branches: 
      - '*'

jobs:
 
  test: #PYTEST
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository 
        uses: actions/checkout@v4
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install Requirements
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install pylint
          for FILE in $(find . -name 'requirements.txt'); do
            pip install -r $FILE
          done
        
      - name: Run pytest
        run: |
          pytest
        continue-on-error: true
      
      - name: Record test results
        if: '!cancelled()'
        run: |
          [ ! -f .util/pytest_scores.txt ] && touch '.util/pytest_scores.txt'
          pytest -r N --tb=no > .util/pytest_scores.txt || true

        
  lint:  #PYLINT 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository 
        uses: actions/checkout@v4
      
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install Requirements
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
      
      # pylint scores
      - name: Create pylint_scores
        if: '!cancelled()'
        run: |
          :> .util/pylint_scores.txt

      # Run Pylint and Get output in file
      - name: Run Pylint
        if: '!cancelled()'
      #   run: |
      #     find . \( -name '*.py' ! -name 'test*.py' \) \
      #     -exec pylint {} \; >> .util/pylint_scores.txt

      # - name: Run pylint
        run: |
          pylint --fail-under=7 $(git ls-files '*.py')
      
      # Convert Pylint scores to JSON
      - name: Convert Pylint scores to JSON
        if: '!cancelled()'
        run: python .util/parse_raw_python.py --input .util/pylint_scores.txt --output .util/pylint_scores.json --type pylint

      # Get the avg_score from pylint_scores.json
      - name: Obtain avg_score from JSON
        if: '!cancelled()'
        run: |
          echo "AVG_SCORE=$(jq '.avg_score' .util/pylint_scores.json)" >> $GITHUB_ENV
        env:
          CODE_QUALITY: ${{ env.AVG_SCORE }}
          BADGE_PATH: .github/badges/avg_score.svg 

      # Generate the badge for avg_score
      - name: Generate the badge SVG image for avg_score
        if: '!cancelled()'
        uses: emibcn/badge-action@v1
        id: avg_score_badge
        with:
          label: 'Pylint Score: '
          status: ${{ format('{0}/10', env.AVG_SCORE) }}
          color: 'blue'
          path: .github/badges/avg_score.svg
          scale: 1.5
      - name: Upload badge as artefact
        if: '!cancelled()'
        uses: actions/upload-artifact@v2
        with:
          name: badge
          path: .github/badges/avg_score.svg
          if-no-files-found: ignore
 

  # lint_badge:
  #   needs: lint
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout Repository
  #       uses: actions/checkout@v4

  #     - name: Create destination directory for lint badge
  #       env:
  #         BADGE_PATH: .github/badges/lint_badge.svg
  #       run: mkdir -p "${BADGE_PATH%/*}"

  #     - name: Generate the lint badge SVG image
  #       uses: emibcn/badge-action@v1
  #       id: lint_badge
  #       with:
  #         label: 'Pylint Score: '
  #         status: ${{ format('{0}/10', env.AVG_SCORE) }}
  #         color: 'green'
  #         path: .github/badges/avg_score.svg
  #         scale: 1.5

  #     - name: Upload lint badge as artifact
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: lint_badge
  #         path: .github/badges/lint_badge.svg
  #         if-no-files-found: ignore

  pytest_badge:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Create destination directory for pytest badge
        env:
          BADGE_PATH: .github/badges/pytest_badge.svg
        run: mkdir -p "${BADGE_PATH%/*}"

      - name: Generate the pytest badge SVG image
        uses: emibcn/badge-action@v1
        id: pytest_badge
        with:
          label: 'Pytest:'
          status: 'Completed'
          color: 'blue'
          path: .github/badges/pytest_badge.svg
          scale: 1.5

      - name: Upload pytest badge as artifact
        uses: actions/upload-artifact@v3
        with:
          name: pytest_badge
          path: .github/badges/pytest_badge.svg
          if-no-files-found: ignore


  # badge: 
  #   needs: [lint]
  #   runs-on: ubuntu-latest

  #   steps: 
  #     - name: Checkout Repository 
  #       uses: actions/checkout@v4
      
  #     # Create the directory where badges will be saved, if needed
  #     - name: Create destination directory for badge
  #       env:
  #         BADGE_PATH: .github/badges/lint_test.svg
  #       run: mkdir -p "${BADGE_PATH%/*}"

  #     # Display build completed 
  #     - name: Generate the badge SVG image
  #       uses: emibcn/badge-action@v1
  #       id: lint_test_badge
  #       with:
  #         label: 'Complete Build: '
  #         status: 'Completed'
  #         color: 'blue'
  #         path: .github/badges/lint_test.svg
  #         scale: 1.5
    
  #     - name: Upload badge as artifact
  #       uses: actions/upload-artifact@v2
  #       with:
  #         name: badge
  #         path: .github/badges/lint_test.svg
  #         if-no-files-found: ignore
     
  #     - name: Committing logs and badge to the repository
  #       if: github.repository != 'sigma-labs-xyz/coursework-template'
  #       run: |
  #         git config --global user.name "FarihaChoudhury"
  #         git config --global user.email "farihac2002@gmail.com"
  #         git pull
  #         git add .github/badges/lint_test.svg
  #         git checkout main
  #         git diff-index --quiet HEAD || git commit -am "Update Complete build"
  #         git push